version: '3.8'
services:
  bookworm-config-server:
    image: bookworm-config-server
    ports:
      - "8000:8000"
    networks:
      - network-dev

  bookworm-discovery-server:
    image: bookworm-discovery-server
    ports:
      - "8761:8761"
    networks:
      - network-dev

  bookworm-zipkin-server:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - network-dev

  bookworm-gateway:
    image: bookworm-gateway
    ports:
      - "8001:8001"
    networks:
      - network-dev

  bookworm-database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: dada
      MYSQL_DATABASE: bookworm
      MYSQL_USER: worm
      MYSQL_PASSWORD: worm1234!@#$
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network-dev

  bookworm-auth:
    image: bookworm-auth
    ports:
      - "8081:8081"
    environment:
      spring.profiles.active: dev
    networks:
      - network-dev

volumes:
  mysql_data:

networks:
  network-dev: